services:
  workcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa_test_workcontainer
    restart: unless-stopped
    env_file:
      - "../.env.devcontainer"
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html:cached
    networks:
      - qa_test_network
    depends_on:
      - sqlserver
    expose:
      - 9000
  web:
    image: nginx:alpine
    container_name: qa_test_web
    restart: unless-stopped
    env_file:
      - "../.env.devcontainer"
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - qa_test_network
    depends_on:
      - workcontainer
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qa_test_sql
    restart: unless-stopped
    user: "mssql"
    env_file:
      - "../.env.devcontainer"
    ports:
      - "1433:1433"
    networks:
      - qa_test_network
    volumes:
      - qa_test_data:/var/opt/mssql

volumes:
  qa_test_data:
    name: qa_test_data

networks:
  qa_test_network:
